
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 武器表
    /// </summary>
    public demo.TbWeapon TbWeapon {get; }
    /// <summary>
    /// 道具表
    /// </summary>
    public demo.TbItem TbItem {get; }
    /// <summary>
    /// 鱼表
    /// </summary>
    public demo.TbFish TbFish {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbWeapon = new demo.TbWeapon(loader("demo_tbweapon"));
        TbItem = new demo.TbItem(loader("demo_tbitem"));
        TbFish = new demo.TbFish(loader("demo_tbfish"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbWeapon.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbFish.ResolveRef(this);
    }
}

}

